### ISSUE TITLE
Questions on the software

### ISSUE THREAD

**Issue by ABanaeiEsfahani** [fosterlab/PrInCE-Matlab#1]
Hello,

I have two questions about the tool. Could you please help me with them?
1. What is "Major_protein_groups.csv" exactly? I could not find any description on this.
2. Is there any chance to run your tool an a bacterium like E.coli where we don't have a good reference like CORUM? By just using the string database for example?

Thanks and best,
Amir

**Comment by GregStacey** [comment]
Hi Amir,

Yeah, of course! I'm happy to help.

1. Major_protein_groups.csv is a list of all protein groups, as output by
MaxQuant. (A discussion of what "protein groups" are is here
http://www.nature.com/nprot/journal/v11/n12/box/nprot.2016.136_BX2.html. In
brief they're groups of proteins that MaxQuant can't tell apart.)
Major_protein_groups.csv has a header, is comma separated, and each group
is on a separate line. Note that this file is optional. You're right that
there's no documentation for this file - I'll fix that!

2. Yes, it is possible to run PrInCE on non-mammalian data like E coli.
Using the STRING database isn't possible, though, since PrInCE needs
reference complexes, not just protein pairs. We've used the IntAct database
with success. Our recent paper includes a discussion of how IntAct compares
to CORUM (http://rdcu.be/xy9p, Figure 3, supplementary Figures). In
principle you can use an set of reference complexes, though - just make
sure that there's enough overlap between the proteins in your data and the
reference complexes. If only a handful of proteins overlap PrInCE will not
have enough data to make good predictions!

Thanks. Let me know if you have any more questions.

-greg

**Comment by ABanaeiEsfahani** [comment]
Hi Greg,

Thanks for your help. Just a follow up on the first question. I only use proteotypic peptides in my dataset. therefore I don't have any protein groups in that sense. I just deleted "Major_protein_groups.csv" from both input file and experimental design document. However, I get an error saying this file is missing. How can I run the tool with out this file? Does that affect the analysis ? Your help would be highly appreciated.

Best,
Amir

**Comment by GregStacey** [comment]
Hi Amir - Sorry about that. It should be possible to run without the
Major_protein_groups file. What error message are you getting?

In "experimental_design.rtf", delete the filename after "Major protein
groups filename:" and try running. That might resolve it.

If it doesn't, can you send the "logfile.txt" to me (
richard.greg.stacey@gmail.com)? Thanks very much!

-greg

**Comment by smdb21** [comment]
Hi! I have very basic questions about the software:

- Where do I put my input files? I am using the standalone windows version. I run it, but I don't know where to put my files. Somewhere I read "on the input folder", but I don't know where it is.

- I intend to use the software with just one condition, is that ok? 

- Also, does it requires more than 1 replicate? 

- Can I use NSAF values in the input file?

Thank you in advance.
Salva.

**Comment by GregStacey** [comment]
No worries - happy to help.

- Input files (condition1.csv, condition2.csv, allComplexes.txt, ...) should go in the "Input" folder. If standalone isn't making the "Input" folder you can do so yourself by creating a new folder called "Input" in the main directory (the exact name "Input" is important).
- Yup, one condition is fine.
- A single replicate is also fine.
- NSAF should be fine, although I've never tried it. In general the code can handle data quantified using any quantitation method, although noisier quantitation methods will obviously yield noisier data that will affect the quality of the interactome.

**Comment by smdb21** [comment]
Thank you for your response. I got it to run right now, although I get an error (see below).
However, there were a couple of extra things I had to do, so maybe this can be useful for other Windows users.
Specifically, I had to create the "Input" folder (with a capital "I", as you said) at "C:\Program Files\prince\application\Input", that is, in the "application" subfolder.
Then, using Windows 10, I had problems of permissions, so I had to give Full control in the security options for the prince folder and subfolders.

While running, I got this error: 
`While setting the 'YLim' property of 'Axes':    
Value must be a 1x2 vector of numeric type in which the second element is larger than the first and may be Inf.  
Error in => prince.m at line 61.`

**Comment by smdb21** [comment]
This is the log file:

```
GaussBuild.m

    0. Initialize  ...  0.01 seconds

    1. Read input data  ...  3.55 seconds

    2. Clean the chromatograms  ...  0.57 seconds

    3. Fit 1-5 Gaussians on each cleaned chromatogramStarting parallel pool (parpool) using the 'local' profile ... connected to 4 workers.

    re-fitting contaminant_KERATIN22...

    re-fitting P35908...

    re-fitting P04264...
    re-fitting contaminant_KERATIN22...
    re-fitting P35908...
    re-fitting P35908...
    re-fitting contaminant_KERATIN22...
    fit P35908 with 3 Gaussians, R^2=0.12
    re-fitting P35527...
    re-fitting P35527...
    re-fitting P35527...
    fit P35527 with 4 Gaussians, R^2=0.82
    fit contaminant_KERATIN22 with 4 Gaussians, R^2=0.59

    fit P62937 with 2 Gaussians, R^2=0.95
    fit P04264 with 4 Gaussians, R^2=0.86
    fit P13645 with 5 Gaussians, R^2=0.88
  ...  107.45 seconds

    4. Write outputGauss_Build: writeOutput: SEC fitting failed. Size of Complex will be zero.
  ...  0.11 seconds

    5. Make figuresError using matlab.graphics.axis.Axes/set
While setting the 'YLim' property of 'Axes':
Value must be a 1x2 vector of numeric type in which the second element is larger than the first and may be Inf

Error in ylim (line 44)


Error in makeFigures_gaussbuild (line 271)


Error in GaussBuild (line 268)


Error in prince (line 61)


MATLAB:hg:shaped_arrays:LimitsWithInfsPredicate
Error writing to output stream.
iostream stream error
```

**Comment by GregStacey** [comment]
Thanks for reporting the error! The Windows standalone is a build behind. I'll update it asap and post here when that's done.

Also, it looks like only 6 proteins were fit with Gaussians. These should be proteins with enough data for fitting (at least 5 non-missing fractions after imputing singletons). Does that sound right for your data?

**Comment by smdb21** [comment]
Thanks! let me know when the new version is available.
I have much more proteins than 6 with non-missing fractions in my input data file. Here you can see my input file of one of my experiments. 
[condition1.zip](https://github.com/fosterlab/PrInCE-Matlab/files/3369709/condition1.zip)

**Comment by GregStacey** [comment]
I updated the code and you can download the new Windows standalone at https://drive.google.com/open?id=1vFgY8Wi8SIr9zNliAJC666IelBbhmyIY. Unfortunately it's too big for github's 100MB limit.

I checked and the new version runs without errors on your data. There are around 1000 interactions using the default values (precision = 50%). Let me know if it works for you.

The error was caused by an assumption that values <0.05 could be rounded down to 0. This is reasonable for SILAC data but it missed most of your data. 

(Just a thought as I ran your data: you have a large range of values in your data (10^-5 to 10^-1) and many of the smaller values are from proteins with a lot of missing data. They might be gumming things up. Removing them might help. For example setting all values less than 10^-3 (or whatever) to NA.)
